/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore_for_file: public_member_api_docs

/// App specific icons for use in the presentation layer.
class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData addIconFilled = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData bookmarkFilled = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData bookmark = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
  static const IconData comment = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
  static const IconData heartFilled = IconData(
    0xe804,
    fontFamily: _kFontFam,
  );
  static const IconData heart = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
  static const IconData homeFilled = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData home = IconData(
    0xe807,
    fontFamily: _kFontFam,
  );
  static const IconData messenger = IconData(
    0xe808,
    fontFamily: _kFontFam,
  );
  static const IconData more = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
  static const IconData plus = IconData(
    0xe80a,
    fontFamily: _kFontFam,
  );
  static const IconData reels = IconData(
    0xe80b,
    fontFamily: _kFontFam,
  );
  static const IconData searchFilled = IconData(
    0xe80c,
    fontFamily: _kFontFam,
  );
  static const IconData search = IconData(
    0xe80d,
    fontFamily: _kFontFam,
  );
  static const IconData share = IconData(
    0xe80e,
    fontFamily: _kFontFam,
  );
  static const IconData shop = IconData(
    0xe80f,
    fontFamily: _kFontFam,
  );
}
